/**
 * The GENRL package's BankLkup ids and their exact bank names.
 *
 * A GENRL bank stores no name of its own; the names live in the game's audio code. They are taken verbatim
 * from gta-reversed source/game_sa/Audio/Enums/eSoundBank.h, which is the authoritative id -> name map
 * (SND_BANK_GENRL_SINGLEPROP = 120, SND_BANK_GENRL_VEHICLE_GEN = 138, ...). The GENRL package occupies the
 * BankLkup ids 7..143 (137 banks - the count genrlBanks reports for this install); FEET is 0..6 and
 * PAIN_A/SCRIPT follow at 144+.
 *
 * Source: https://github.com/gta-reversed/gta-reversed/blob/master/source/game_sa/Audio/Enums/eSoundBank.h
 */

/** First BankLkup id of the GENRL package (FEET owns 0..6). */
export const GENRL_FIRST_BANK_ID = 7;

/** Every GENRL bank id -> its exact gta-reversed enum name, indexed by (id - GENRL_FIRST_BANK_ID). */
export const GENRL_BANK_NAMES: readonly string[] = [
  'SND_BANK_GENRL_90S_D', // 7
  'SND_BANK_GENRL_90S_P', // 8
  'SND_BANK_GENRL_AIPROP', // 9
  'SND_BANK_GENRL_AIRPORT_D', // 10
  'SND_BANK_GENRL_AIRPORT_P', // 11
  'SND_BANK_GENRL_APACHE', // 12
  'SND_BANK_GENRL_APACHE_D', // 13
  'SND_BANK_GENRL_ATV_D', // 14
  'SND_BANK_GENRL_ATV_P', // 15
  'SND_BANK_GENRL_BELAIR_D', // 16
  'SND_BANK_GENRL_BELAIR_P', // 17
  'SND_BANK_GENRL_BICYCLE_D', // 18
  'SND_BANK_GENRL_BICYCLE_P', // 19
  'SND_BANK_GENRL_BOAT_CRUISER_D', // 20
  'SND_BANK_GENRL_BOAT_INBOARD_D', // 21
  'SND_BANK_GENRL_BOAT_INBOARD_P', // 22
  'SND_BANK_GENRL_BOAT_SPEEDBOAT_D', // 23
  'SND_BANK_GENRL_BOAT_V12_D', // 24
  'SND_BANK_GENRL_BUICK_D', // 25
  'SND_BANK_GENRL_BUICK_P', // 26
  'SND_BANK_GENRL_BULLET_HITS', // 27
  'SND_BANK_GENRL_BULLET_PASS_FIRST', // 28
  'SND_BANK_GENRL_BULLET_PASS_2', // 29
  'SND_BANK_GENRL_BULLET_PASS_3', // 30
  'SND_BANK_GENRL_BULLET_PASS_4', // 31
  'SND_BANK_GENRL_BUS_D', // 32
  'SND_BANK_GENRL_BUS_P', // 33
  'SND_BANK_GENRL_CADILLAC_D', // 34
  'SND_BANK_GENRL_CADILLAC_P', // 35
  'SND_BANK_GENRL_CHAINSAW_P', // 36
  'SND_BANK_GENRL_COBRA_D', // 37
  'SND_BANK_GENRL_COBRA_P', // 38
  'SND_BANK_GENRL_COLLISIONS', // 39
  'SND_BANK_GENRL_COPBIKE_D', // 40
  'SND_BANK_GENRL_COPBIKE_P', // 41
  'SND_BANK_GENRL_COUPE_D', // 42
  'SND_BANK_GENRL_COUPE_P', // 43
  'SND_BANK_GENRL_CRANE_P', // 44
  'SND_BANK_GENRL_CUTLASS_D', // 45
  'SND_BANK_GENRL_CUTLASS_P', // 46
  'SND_BANK_GENRL_DIRTBIKE_D', // 47
  'SND_BANK_GENRL_DIRTBIKE_P', // 48
  'SND_BANK_GENRL_DODGE_D', // 49
  'SND_BANK_GENRL_DODGE_P', // 50
  'SND_BANK_GENRL_DOORS', // 51
  'SND_BANK_GENRL_EXPLOSIONS', // 52
  'SND_BANK_GENRL_FASTPROP', // 53
  'SND_BANK_GENRL_FASTPROP_D', // 54
  'SND_BANK_GENRL_FORD_T_D', // 55
  'SND_BANK_GENRL_FORD_T_P', // 56
  'SND_BANK_GENRL_FORKLIFT_D', // 57
  'SND_BANK_GENRL_FORKLIFT_P', // 58
  'SND_BANK_GENRL_FRONTEND_GAME', // 59
  'SND_BANK_GENRL_FRONTEND_MENU', // 60
  'SND_BANK_GENRL_GOKART_D', // 61
  'SND_BANK_GENRL_GOKART_P', // 62
  'SND_BANK_GENRL_GOLF_D', // 63
  'SND_BANK_GENRL_GOLF_P', // 64
  'SND_BANK_GENRL_GOLFCART_P', // 65
  'SND_BANK_GENRL_HAIRCUT_V1', // 66
  'SND_BANK_GENRL_HAIRCUT_V2', // 67
  'SND_BANK_GENRL_HARVESTER_D', // 68
  'SND_BANK_GENRL_HARVESTER_P', // 69
  'SND_BANK_GENRL_HEAVY_V8_D', // 70
  'SND_BANK_GENRL_HEAVY_V8_P', // 71
  'SND_BANK_GENRL_HONDA_D', // 72
  'SND_BANK_GENRL_HONDA_P', // 73
  'SND_BANK_GENRL_HORN', // 74
  'SND_BANK_GENRL_HOTROD_D', // 75
  'SND_BANK_GENRL_HOTROD_P', // 76
  'SND_BANK_GENRL_HOVERCRAFT_D', // 77
  'SND_BANK_GENRL_HOVERCRAFT_P', // 78
  'SND_BANK_GENRL_ICEVAN_P', // 79
  'SND_BANK_GENRL_JALOPY_D', // 80
  'SND_BANK_GENRL_JALOPY_P', // 81
  'SND_BANK_GENRL_LOADING', // 82
  'SND_BANK_GENRL_MACKTRUCK_D', // 83
  'SND_BANK_GENRL_MACKTRUCK_P', // 84
  'SND_BANK_GENRL_MAVERICK', // 85
  'SND_BANK_GENRL_MERC_D', // 86
  'SND_BANK_GENRL_MERC_P', // 87
  'SND_BANK_GENRL_MODEL_T_D', // 88
  'SND_BANK_GENRL_MODEL_T_P', // 89
  'SND_BANK_GENRL_MONSTER_D', // 90
  'SND_BANK_GENRL_MONSTER_P', // 91
  'SND_BANK_GENRL_MUSTANG_D', // 92
  'SND_BANK_GENRL_MUSTANG_P', // 93
  'SND_BANK_GENRL_PACARD_D', // 94
  'SND_BANK_GENRL_PACARD_P', // 95
  'SND_BANK_GENRL_PADDY_D', // 96
  'SND_BANK_GENRL_PADDY_P', // 97
  'SND_BANK_GENRL_PATHFINDER_D', // 98
  'SND_BANK_GENRL_PATHFINDER_P', // 99
  'SND_BANK_GENRL_PONTIAC_D', // 100
  'SND_BANK_GENRL_PONTIAC_P', // 101
  'SND_BANK_GENRL_PORSCHE_D', // 102
  'SND_BANK_GENRL_PORSCHE_P', // 103
  'SND_BANK_GENRL_R22', // 104
  'SND_BANK_GENRL_RAIN', // 105
  'SND_BANK_GENRL_RC_CAR_D', // 106
  'SND_BANK_GENRL_RC_CAR_P', // 107
  'SND_BANK_GENRL_RC_HELI_D', // 108
  'SND_BANK_GENRL_RC_HELI_P', // 109
  'SND_BANK_GENRL_RC_PLANE_D', // 110
  'SND_BANK_GENRL_RC_PLANE_P', // 111
  'SND_BANK_GENRL_RC_TANK_D', // 112
  'SND_BANK_GENRL_RC_TANK_P', // 113
  'SND_BANK_GENRL_RS427_D', // 114
  'SND_BANK_GENRL_RS427_P', // 115
  'SND_BANK_GENRL_SALOON_D', // 116
  'SND_BANK_GENRL_SALOON_P', // 117
  'SND_BANK_GENRL_SCOOTER_D', // 118
  'SND_BANK_GENRL_SCOOTER_P', // 119
  'SND_BANK_GENRL_SINGLEPROP', // 120
  'SND_BANK_GENRL_SKATEBOARD_P', // 121
  'SND_BANK_GENRL_SPORT_D', // 122
  'SND_BANK_GENRL_SPORT_P', // 123
  'SND_BANK_GENRL_SPORTSBIKE_D', // 124
  'SND_BANK_GENRL_SPORTSBIKE_P', // 125
  'SND_BANK_GENRL_SWEEPER_D', // 126
  'SND_BANK_GENRL_SWEEPER_P', // 127
  'SND_BANK_GENRL_SWIMMING', // 128
  'SND_BANK_GENRL_TEMP_D', // 129
  'SND_BANK_GENRL_TEMP_P', // 130
  'SND_BANK_GENRL_TRAIN_D', // 131
  'SND_BANK_GENRL_TRAIN_P', // 132
  'SND_BANK_GENRL_TRAM_D', // 133
  'SND_BANK_GENRL_TWINPROP', // 134
  'SND_BANK_GENRL_TWINPROP_D', // 135
  'SND_BANK_GENRL_VAN_D', // 136
  'SND_BANK_GENRL_VAN_P', // 137
  'SND_BANK_GENRL_VEHICLE_GEN', // 138
  'SND_BANK_GENRL_VTWINBIKE_D', // 139
  'SND_BANK_GENRL_VTWINBIKE_P', // 140
  'SND_BANK_GENRL_VW_VAN_D', // 141
  'SND_BANK_GENRL_VW_VAN_P', // 142
  'SND_BANK_GENRL_WEAPONS', // 143
];

/**
 * The exact bank name for a GENRL BankLkup id, or null when the id lies outside the 137-bank GENRL package.
 */
export function genrlBankName(globalBankId: number): null | string {
  const index = globalBankId - GENRL_FIRST_BANK_ID;

  return Number.isInteger(index) && index >= 0 && index < GENRL_BANK_NAMES.length
    ? (GENRL_BANK_NAMES[index] ?? null)
    : null;
}
