import http from "node:http";
import { exec, execFile, spawn } from "node:child_process";
import { randomUUID } from "node:crypto";
import { createReadStream, existsSync, mkdirSync, readdirSync, rmSync, promises as fs } from "node:fs";
import { tmpdir } from "node:os";
import path from "node:path";
import { createVideoExporter } from "./video-export.mjs";

const gameRoot = path.resolve(process.env.GAME_ROOT || process.argv[2] || "../GTA San Andreas");
const siteRoot = path.resolve("dist");
const dffLoaderRoot = path.resolve("../tools/DFF-Loader/src");
const recordingsRoot = path.resolve(process.env.RECORDINGS_ROOT || path.join(gameRoot, "flight_recordings"));
/** Route A baked map pak (regenerated by tools/opensa/scripts/bake-map.mts). */
const mapPakRoot = process.env.MAP_PAK_ROOT || path.resolve("..", "tools", "opensa", "map-pak");
const opensaRoot = path.resolve("..", "tools", "opensa");
const routePakRoot = path.join(opensaRoot, "map-pak-routes");
const port = Number(process.env.PORT || 4173);
const bakeJobs = new Map();
let baking = false;
const chromeCandidates = [
  "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe",
  path.join(process.env.LOCALAPPDATA ?? "", "Google", "Chrome", "Application", "chrome.exe"),
  "C:\\Program Files (x86)\\Microsoft\\Edge\\Application\\msedge.exe",
  "C:\\Program Files\\Microsoft\\Edge\\Application\\msedge.exe",
];
const chromium = chromeCandidates.find((candidate) => candidate && existsSync(candidate));
const videoExporter = createVideoExporter({ origin: `http://127.0.0.1:${port}`, recordingsRoot,
  opensaRoot, chromiumPath: chromium, ffmpegExecutable: process.env.FFMPEG_PATH || "ffmpeg" });

// The original-install routes are used by the offline baker only. Index lazily so replay can start
// with no GTA installation present; the browser runtime requests only /map-pak and recordings.
const installFiles = new Map();
async function indexInstall(directory = gameRoot, prefix = "") {
  for (const entry of await fs.readdir(directory, { withFileTypes: true })) {
    if (entry.isSymbolicLink()) continue;
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    const absolute = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      if (/^(flight_recordings|screens|user files)$/i.test(entry.name)) continue;
      await indexInstall(absolute, relative);
    } else if (entry.isFile()) {
      const stat = await fs.stat(absolute);
      installFiles.set(relative.toLowerCase(), { path: relative.replaceAll("\\", "/"), absolute, size: stat.size });
    }
  }
}
const imgCandidates = [
  path.join(gameRoot, "models", "gta3.img"),
  path.join(gameRoot, "models", "gta_int.img"),
  path.join(gameRoot, "SAMP", "SAMP.img"),
  path.join(gameRoot, "SAMP", "custom.img")
];
const archiveEntries = new Map();
const archiveNames = [];

const send = (res, code, body, type = "text/plain; charset=utf-8") => { res.writeHead(code, { "Content-Type": type, "Cache-Control": "no-store" }); res.end(body); };
const safe = value => value && !value.includes("..") && !value.includes("\\") && !value.startsWith("/") ? value : null;
const contentType = file => file.endsWith(".html") ? "text/html; charset=utf-8"
  : file.endsWith(".js") ? "text/javascript; charset=utf-8"
  : file.endsWith(".css") ? "text/css; charset=utf-8"
  : file.endsWith(".json") || file.endsWith(".webmanifest") ? "application/json; charset=utf-8"
  : file.endsWith(".csv") ? "text/csv; charset=utf-8"
  : file.endsWith(".wav") ? "audio/wav"
  : file.endsWith(".png") ? "image/png"
  : file.endsWith(".svg") ? "image/svg+xml"
  : file.endsWith(".woff2") ? "font/woff2"
  : "application/octet-stream";
async function mapsManifest() {
  const text = await fs.readFile(path.join(gameRoot, "data", "gta.dat"), "utf8");
  const items = [];
  for (const raw of text.split(/\r?\n/)) {
    const line = raw.trim(); if (!line || line.startsWith("#")) continue;
    const match = /^(IDE|IPL)\s+(.+)$/i.exec(line); if (!match) continue;
    const relative = match[2].trim().replaceAll("\\", "/").replace(/^data\//i, "");
    if (/\.(ipl|ide)$/i.test(relative)) items.push(relative);
  }
  return [...new Set(items)];
}
let mapFiles = [];
let binaryIpls = [];
let gameSourcePromise = null;
function ensureGameSource() {
  if (gameSourcePromise) return gameSourcePromise;
  gameSourcePromise = (async () => {
    await indexInstall();
    for (const imgPath of imgCandidates) {
      try {
        const img = await fs.open(imgPath, "r");
        const header = Buffer.alloc(8);
        await img.read(header, 0, 8, 0);
        if (header.subarray(0, 4).toString("ascii") !== "VER2") {
          await img.close();
          continue;
        }
        const count = header.readUInt32LE(4);
        const directory = Buffer.alloc(count * 32);
        await img.read(directory, 0, directory.length, 8);
        for (let i = 0; i < count; i += 1) {
          const at = i * 32;
          const name = directory.subarray(at + 8, at + 32).toString("ascii").replace(/\0.*$/, "").toLowerCase();
          // Later archives deliberately override earlier ones.
          archiveEntries.set(name, {
            img, archive: path.basename(imgPath), offset: directory.readUInt32LE(at) * 2048,
            size: directory.readUInt16LE(at + 4) * 2048
          });
        }
        archiveNames.push(path.relative(gameRoot, imgPath).replaceAll("\\", "/"));
      } catch (error) {
        if (imgPath.endsWith("gta3.img")) throw error;
      }
    }
    mapFiles = await mapsManifest();
    // Only gta.dat companions plus the unlocked Truth's farm state belong to the map manifest.
    const mapBases = new Set(mapFiles.filter(name => /\.ipl$/i.test(name))
      .map(name => path.basename(name, path.extname(name)).toLowerCase()));
    binaryIpls = [...archiveEntries.keys()].filter(name => {
      const streamed = /^(.+)_stream\d+\.ipl$/i.exec(name);
      return (streamed && mapBases.has(streamed[1].toLowerCase())) || name === "truthsfarm.ipl";
    });
  })().catch(error => { gameSourcePromise = null; throw error; });
  return gameSourcePromise;
}

/**
 * Pick the newest recording file that is NOT growing, so the replay never streams a file the recorder is
 * still appending to. `dated` is newest-first; if the newest is still being written, walk back. When every
 * candidate looks busy (a very fast recorder) the newest is returned anyway rather than failing.
 */
async function chooseSettledRecording(dated) {
  const sizeNow = new Map();
  await Promise.all(dated.map(async entry => {
    sizeNow.set(entry.name, (await fs.stat(path.join(recordingsRoot, entry.name))).size);
  }));
  await new Promise(resolve => setTimeout(resolve, 120));
  const settled = [];
  for (const entry of dated) {
    const size = (await fs.stat(path.join(recordingsRoot, entry.name))).size;
    settled.push({ ...entry, growing: size !== sizeNow.get(entry.name) });
  }
  return settled.find(entry => !entry.growing) ?? settled[0];
}

const server = http.createServer(async (req, res) => {
  try {
    let pathname;
    let requestUrl;
    try {
      requestUrl = new URL(req.url, `http://${req.headers.host}`);
      pathname = decodeURIComponent(requestUrl.pathname);
    } catch {
      return send(res, 400, "Invalid URL");
    }
    if (await videoExporter.handle(req, res, pathname)) return;
    // Only this loopback page may request a bake. The browser sends the selected recording, so
    // drag-and-drop files work without exposing arbitrary local paths to the server.
    if (pathname === "/route-bake" && req.method === "POST") {
      if (req.headers.origin !== `http://127.0.0.1:${port}`) return send(res, 403, "Forbidden");
      if (baking) return send(res, 409, "A route bake is already running");
      const chunks = [];
      let size = 0;
      for await (const chunk of req) {
        size += chunk.length;
        if (size > 32 * 1024 * 1024) return send(res, 413, "Recording is too large");
        chunks.push(chunk);
      }
      let input;
      try { input = JSON.parse(Buffer.concat(chunks).toString("utf8")); }
      catch { return send(res, 400, "Invalid JSON"); }
      if (!input || typeof input.csv !== "string" || !input.csv.includes("local_timestamp,") || input.csv.length > 16 * 1024 * 1024) {
        return send(res, 400, "Invalid FlightRecorder CSV");
      }
      baking = true;
      const id = randomUUID();
      const directory = path.join(routePakRoot, id);
      try {
        await fs.mkdir(directory, { recursive: true });
        await fs.writeFile(path.join(directory, "recording.csv"), input.csv);
      } catch (error) {
        baking = false;
        throw error;
      }
      const job = { state: "running", message: "Starting route bake", id };
      bakeJobs.set(id, job);
      const child = spawn(process.execPath, [path.join(opensaRoot, "node_modules", "tsx", "dist", "cli.mjs"),
        "scripts/bake-map.mts", directory, "--recording", path.join(directory, "recording.csv")],
        { cwd: opensaRoot, env: { ...process.env, GAME_SOURCE_BASE: `http://127.0.0.1:${port}/game-src` }, windowsHide: true });
      for (const stream of [child.stdout, child.stderr]) {
        stream.on("data", chunk => {
          const lines = String(chunk).trim().split(/\r?\n/).filter(Boolean);
          if (lines.length) job.message = lines[lines.length - 1].slice(0, 300);
        });
      }
      child.on("error", error => { job.state = "failed"; job.message = error.message; baking = false; });
      child.on("exit", code => {
        if (job.state === "running") {
          job.state = code === 0 && existsSync(path.join(directory, "index.json")) ? "ready" : "failed";
          if (job.state === "failed") job.message = `Bake exited with code ${code}: ${job.message}`;
        }
        baking = false;
      });
      return send(res, 202, JSON.stringify({ id }), "application/json; charset=utf-8");
    }
    if (pathname.startsWith("/route-bake/") && req.method === "GET") {
      const id = pathname.slice("/route-bake/".length);
      const job = bakeJobs.get(id);
      return job ? send(res, 200, JSON.stringify(job), "application/json; charset=utf-8") : send(res, 404, "Unknown bake");
    }
    if (pathname.startsWith("/route-pak/") && req.method === "GET") {
      const match = /^\/route-pak\/([0-9a-f-]{36})\/(.+)$/.exec(pathname);
      if (!match || !safe(match[2])) return send(res, 403, "Forbidden");
      const file = path.join(routePakRoot, match[1], match[2]);
      const content = await fs.readFile(file);
      return send(res, 200, content, contentType(file));
    }
    if (pathname === "/webgpu-report" && req.method === "POST") {
      let body = "";
      let size = 0;
      for await (const chunk of req) {
        size += chunk.length;
        if (size > 1024 * 1024) return send(res, 413, "Report is too large");
        body += chunk;
      }
      await fs.writeFile(path.join(process.cwd(), "webgpu-report.json"), body).catch(() => {});
      // Keep the full boot/reload sequence; the single latest report cannot explain intermittent device loss.
      let event;
      try { event = JSON.parse(body); } catch { event = { invalidReport: body }; }
      await fs.appendFile(path.join(process.cwd(), "webgpu-events.jsonl"),
        `${JSON.stringify({ ...event, recordedAt: new Date().toISOString() })}\n`).catch(() => {});
      console.log(`[webgpu-report] ${body}`);
      return send(res, 200, "ok");
    }
    if (pathname.startsWith("/dff-loader-fixed/")) {
      const name = pathname.slice("/dff-loader-fixed/".length);
      if (!/^(DFFLoader|Reader|TXDLoader|ChunkType)\.js$/.test(name)) return send(res, 403, "Forbidden");
      return send(res, 200, await fs.readFile(path.join(dffLoaderRoot, name)), "text/javascript; charset=utf-8");
    }
    // Route A: locally baked map pak (see tools/opensa/scripts/bake-map.mts). Textures/cells/index only.
    if (pathname.startsWith("/map-pak/")) {
      const relative = pathname.slice("/map-pak/".length).replaceAll("\\", "/");
      if (relative.includes("..")) return send(res, 403, "Forbidden");
      const file = path.join(mapPakRoot, relative);
      const content = await fs.readFile(file);
      return send(res, 200, content, relative.endsWith(".json") ? "application/json; charset=utf-8" : "application/octet-stream");
    }
    if (pathname === "/game-src/__index") {
      await ensureGameSource();
      const index = [...installFiles.values()].map(({ path: filePath, size }) => ({ path: filePath, size }));
      return send(res, 200, JSON.stringify(index), "application/json; charset=utf-8");
    }
    if (pathname.startsWith("/game-src/")) {
      await ensureGameSource();
      const requested = pathname.slice("/game-src/".length).replaceAll("\\", "/");
      if (!safe(requested)) return send(res, 403, "Forbidden");
      const file = installFiles.get(requested.toLowerCase());
      if (!file) return send(res, 404, "Missing GTA file");
      const range = /^bytes=(\d+)-(\d*)$/i.exec(req.headers.range || "");
      if (range) {
        const start = Number(range[1]);
        const requestedEnd = range[2] ? Number(range[2]) : file.size - 1;
        const end = Math.min(requestedEnd, file.size - 1);
        if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start < 0 || start > end || start >= file.size) {
          res.writeHead(416, { "Content-Range": `bytes */${file.size}` });
          return res.end();
        }
        res.writeHead(206, {
          "Content-Type": contentType(file.path),
          "Content-Length": end - start + 1,
          "Content-Range": `bytes ${start}-${end}/${file.size}`,
          "Accept-Ranges": "bytes",
          "Cache-Control": "no-store"
        });
        return createReadStream(file.absolute, { start, end }).pipe(res);
      }
      res.writeHead(200, {
        "Content-Type": contentType(file.path),
        "Content-Length": file.size,
        "Accept-Ranges": "bytes",
        "Cache-Control": "no-store"
      });
      return createReadStream(file.absolute).pipe(res);
    }
    if (pathname === "/gta/map-manifest") {
      await ensureGameSource();
      return send(res, 200, JSON.stringify({ text: mapFiles, binary: binaryIpls, archives: archiveNames }), "application/json");
    }
    if (pathname.startsWith("/gta/model/")) {
      await ensureGameSource();
      const name = safe(pathname.slice("/gta/model/".length).toLowerCase()); const entry = name && archiveEntries.get(name);
      if (!entry) return send(res, 404, "Missing GTA archive entry");
      const data = Buffer.alloc(entry.size); await entry.img.read(data, 0, entry.size, entry.offset);
      return send(res, 200, data, "application/octet-stream");
    }
    if (pathname.startsWith("/gta/data/")) {
      const relative = pathname.slice("/gta/data/".length).replaceAll("\\", "/");
      const allowedDat = /^(carcols|water|water1|timecyc|timecycp|plants|procobj|object)\.dat$/i.test(relative);
      if (relative.includes("..") || !(/\.(ipl|ide)$/i.test(relative) || allowedDat)) return send(res, 403, "Forbidden");
      return createReadStream(path.join(gameRoot, "data", relative)).on("error", () => send(res, 404, "Missing GTA data file")).pipe(res);
    }
    // Local-only convenience route. It is intentionally limited to files already
    // written by this recorder; no arbitrary path can be read through the browser.
    if (pathname.startsWith("/local-recording/audio/") && req.method === "GET") {
      const name = pathname.slice("/local-recording/audio/".length);
      if (!/^flight_[A-Za-z0-9._-]+\.wav$/i.test(name) || path.basename(name) !== name) return send(res, 403, "Forbidden");
      const file = path.join(recordingsRoot, name);
      const stat = await fs.stat(file).catch(() => null);
      if (!stat?.isFile()) return send(res, 404, "Audio unavailable");
      const range = /^bytes=(\d+)-(\d*)$/i.exec(req.headers.range || "");
      const start = range ? Number(range[1]) : 0;
      const end = range ? Math.min(range[2] ? Number(range[2]) : stat.size - 1, stat.size - 1) : stat.size - 1;
      if (!Number.isSafeInteger(start) || !Number.isSafeInteger(end) || start < 0 || start > end || end >= stat.size) {
        res.writeHead(416, { "Content-Range": `bytes */${stat.size}` }); return res.end();
      }
      res.writeHead(range ? 206 : 200, { "Content-Type": "audio/wav", "Accept-Ranges": "bytes",
        "Content-Length": end - start + 1, "Cache-Control": "no-store",
        ...(range ? { "Content-Range": `bytes ${start}-${end}/${stat.size}` } : {}) });
      return createReadStream(file, { start, end }).pipe(res);
    }
    if (pathname === "/local-recording/latest.csv") {
      const entries = await fs.readdir(recordingsRoot, { withFileTypes: true }).catch(() => []);
      const files = entries
        .filter(entry => entry.isFile() && /^flight_.*\.csv$/i.test(entry.name));
      if (!files.length) return send(res, 404, "No local flight recordings");
      const dated = await Promise.all(files.map(async entry => ({ name: entry.name, stat: await fs.stat(path.join(recordingsRoot, entry.name)) })));
      dated.sort((a, b) => b.stat.mtimeMs - a.stat.mtimeMs);
      // The recorder APPENDS to the newest file while the player is in the game, so serving it streams a
      // moving target and the browser aborts with ERR_CONTENT_LENGTH_MISMATCH (field 2026-09-25). A growing
      // file is detected structurally: its size changes between two stats a moment apart. When the newest
      // file is still being written, fall back to the newest one that is NOT.
      const chosen = await chooseSettledRecording(dated);
      const audioName = chosen.name.replace(/\.csv$/i, ".wav");
      const audio = await fs.stat(path.join(recordingsRoot, audioName)).catch(() => null);
      res.writeHead(200, { "Content-Type": "text/csv; charset=utf-8", "Cache-Control": "no-store",
        "X-Recording-Name": chosen.name,
        ...(audio?.isFile() ? { "X-Recording-Audio": `/local-recording/audio/${encodeURIComponent(audioName)}` } : {}) });
      return createReadStream(path.join(recordingsRoot, chosen.name)).pipe(res);
    }
    // The replay page is the OpenSA WebGPU build; `/` forwards to it with the query intact so
    // `http://127.0.0.1:4173/?local=latest` (and `?src=`) works unchanged.
    if (pathname === "/") {
      res.writeHead(302, { Location: `/opensa/flight-replay.html${requestUrl.search}` });
      return res.end();
    }
    const requested = pathname === "/" ? "index.html" : pathname.slice(1);
    if (!safe(requested)) return send(res, 403, "Forbidden");
    const file = path.join(siteRoot, requested); const content = await fs.readFile(file);
    send(res, 200, content, contentType(file));
  } catch { send(res, 404, "Not found"); }
});
const url = `http://127.0.0.1:${port}/`;

/**
 * Open the page in Chromium. A FRESH throwaway profile is used every launch.
 *
 * Why not the everyday profile or a persistent dedicated one: Chrome's WebGPU adapter handoff breaks when a
 * profile's GPU caches go bad (measured here: `requestAdapter -> null` in the everyday profile while a fresh
 * profile returns the Arc D3D12 adapter), and a force-killed Chrome can poison a REUSED profile. A new profile
 * per run makes the replay immune to both. The default browser is used when no Chromium is found.
 */
const profileRoot = path.join(process.env.LOCALAPPDATA ?? tmpdir(), "GTASA-StuntTools", "chrome-profiles");
const openBrowser = (target) => {
  if (process.env.NO_OPEN) return;
  if (process.platform === "win32" && chromium) {
    let profile = path.join(profileRoot, `run-${Date.now()}`);
    try {
      mkdirSync(profile, { recursive: true });
      // Keep only the three newest run profiles so the folder does not grow without bound.
      const runs = readdirSync(profileRoot)
        .filter((name) => name.startsWith("run-"))
        .sort()
        .reverse();
      for (const stale of runs.slice(3)) {
        rmSync(path.join(profileRoot, stale), { force: true, recursive: true });
      }
    } catch {
      profile = path.join(tmpdir(), `opensa-replay-${Date.now()}`);
    }
    execFile(chromium, [`--user-data-dir=${profile}`, "--no-first-run", "--no-default-browser-check", target], (error) => {
      if (error) console.log(`请手动打开： ${target}`);
    });
    return;
  }
  const opener = process.platform === "darwin" ? `open "${target}"` : `xdg-open "${target}"`;
  exec(opener, (error) => {
    if (error) console.log(`请手动打开： ${target}`);
  });
};

server.on("error", async error => {
  if (error.code === "EADDRINUSE") {
    // The port is taken. It may be THIS service (then just open it), or a different one — a stale server
    // from another checkout serves another site and shows up as "Not found" on our routes, which is a
    // confusing trap. Probe our own page and say which case it is.
    let ours = false;
    try {
      const probe = await fetch(`${url}opensa/flight-replay.html`, { method: "GET" });
      ours = probe.ok;
    } catch {
      ours = false;
    }
    if (ours) {
      console.log(`本地回放服务已经在运行： ${url}`);
    } else {
      console.log(`端口 ${port} 已被另一个进程占用（不是本项目的回放服务）。`);
      console.log(`请先结束占用 ${port} 的进程（可能是旧项目的 local-server），再重新运行本脚本。`);
      console.log(`否则浏览器打开的会是那个旧服务，访问本项目的页面会显示 Not found。`);
    }
    openBrowser(url);
    process.exitCode = 0;
    return;
  }
  throw error;
});
server.listen(port, "127.0.0.1", () => {
  console.log(`本地回放已启动： ${url}`);
  console.log(`本地最新记录： ${url}?local=latest`);
  openBrowser(url);
});
